GET http://localhost:3000/todo/

###
GET http://localhost:3000/todos/

###
GET http://localhost:3000/todos/?status=TO%20DO

###
GET http://localhost:3000/todos/5/

###
GET http://localhost:3000/agenda/?date=2021-12-12

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 7,
 "todo": "Naa event theme",
 "priority": "HIGH",
 "status": "TO DO",
 "category": "WORK",
 "dueDate": "2023-02-22"
}

###
PUT http://localhost:3000/todos/4/
Content-Type: application/json

{ "status": "DONE" }

###
PUT http://localhost:3000/todos/4/
Content-Type: application/json

{ "priority": "LOW" }